# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-03 05:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='name',
            field=models.CharField(max_length=30, null=True, verbose_name='\u4f5c\u8005'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='updatetime',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='\u66f4\u65b0\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='body',
            field=models.TextField(verbose_name='\u6b63\u6587'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='timestamp',
            field=models.DateTimeField(verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(max_length=150, verbose_name='\u6807\u9898'),
        ),
    ]
