# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-03 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpost_classification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='name',
            new_name='author',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='classification',
            field=models.CharField(max_length=30, null=True, verbose_name='\u5206\u7c7b'),
        ),
    ]
