# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-03 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20160403_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='article',
            name='shortcontent',
            field=models.TextField(max_length=500),
        ),
    ]
