# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-03 18:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20160403_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='bads',
            field=models.IntegerField(default=0, verbose_name='\u8e29'),
        ),
        migrations.AlterField(
            model_name='article',
            name='caption',
            field=models.CharField(max_length=200, verbose_name='\u6807\u9898'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Category', verbose_name='\u5206\u7c7b'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(null=True, verbose_name='\u6b63\u6587'),
        ),
        migrations.AlterField(
            model_name='article',
            name='createtime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='article',
            name='goods',
            field=models.IntegerField(default=0, verbose_name='\u9876'),
        ),
        migrations.AlterField(
            model_name='article',
            name='hits',
            field=models.IntegerField(default=0, verbose_name='\u70b9\u51fb\u6570'),
        ),
        migrations.AlterField(
            model_name='article',
            name='shortcontent',
            field=models.TextField(max_length=500, verbose_name='\u6587\u7ae0\u6458\u8981'),
        ),
        migrations.AlterField(
            model_name='article',
            name='times',
            field=models.IntegerField(default=0, verbose_name='\u9605\u8bfb\u6570'),
        ),
    ]
