# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 06:04
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20160404_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=DjangoUeditor.models.UEditorField(null=True, verbose_name='\u6b63\u6587'),
        ),
    ]
