# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20160404_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(null=True, verbose_name='\u6b63\u6587'),
        ),
    ]
