# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 06:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20160404_1423'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-createtime']},
        ),
    ]
