# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20160404_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='updatetime',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='\u66f4\u65b0\u65f6\u95f4'),
        ),
    ]
